### ISSUE TITLE
consult

### ISSUE THREAD

**Issue by ikrain** [MarihamR/Categorizing-Crises-from-Social-Media-Feeds-Via-Multimodal-Channel-Attention#2]
Hello author! I am a master's student. I was fortunate enough to read an article you published titled "Categorizing Crises From Social Media Feeds via Multimodal Channel Attention". I am very interested in your research. I am also in the research direction in this area, but in We have encountered many difficulties in the process of reproducing your experiment. I hope to apply for the source code from you, and I promise you that your code will be kept confidential and will never be used commercially. Once again, I would like to express my gratitude to you as a student!
      I sincerely hope to get guidance from the teacher, and sincerely wish you success in your work and good health!

**Comment by MarihamR** [comment]
Thank you for you interest, The code is released now.
